### ISSUE TITLE
Rajouter exemple de code pour mushroom

### ISSUE THREAD

**Issue by Brawdunoir** [hekmon/rtetempo#47]
Bonjour !

Merci pour ce plugin très utile !
J’utilise personnellement Mushroom, et je souhaite rajouter des exemples de code dans le README pour cet outil (de la même manière que cela est fait pour Lovelace).

Je fais une PR dans les prochaines minutes.

Bonnes fêtes!

**Comment by sleveille4** [comment]
si ca peut aider, voici ce que j'ai fait pour afficher les infos tempo avec mushroom:

<img width="380" height="333" alt="Image" src="https://github.com/user-attachments/assets/41c13d5f-861a-4d17-933e-15d2d7b13060" />

la couleur des 2 pastilles s'adapte en fonction, et l'ensemble n'est visible que si il reste un jour rouge ou blanc non planifié

```
square: false
type: grid
cards:
  - type: custom:mushroom-title-card
    title: EDF Tempo
    alignment: center
    subtitle_tap_action:
      action: none
    title_tap_action:
      action: none
  - square: false
    type: grid
    cards:
      - type: custom:mushroom-template-card
        primary: Aujourd'hui
        secondary: ""
        icon: mdi:home-lightning-bolt
        icon_color: |-
          {% if (states('sensor.rte_tempo_couleur_actuelle') == "Bleu") %}
            blue
          {% elif (states('sensor.rte_tempo_couleur_actuelle') == "Blanc") %}
            white
          {% elif (states('sensor.rte_tempo_couleur_actuelle') == "Rouge") %}
            red
          {% endif %}
        badge_color: ""
        fill_container: true
        layout: vertical
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
      - type: custom:mushroom-template-card
        primary: Demain
        secondary: ""
        icon: mdi:home-lightning-bolt
        icon_color: |-
          {% if (states('sensor.rte_tempo_prochaine_couleur') == "Bleu") %}
            blue
          {% elif (states('sensor.rte_tempo_prochaine_couleur') == "Blanc") %}
            white
          {% elif (states('sensor.rte_tempo_prochaine_couleur') == "Rouge") %}
            red
          {% endif %}
        badge_color: ""
        fill_container: true
        layout: vertical
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
    columns: 2
  - type: custom:mushroom-template-card
    primary: Jours Restants
    secondary: >-
      Bleu: {{states('sensor.rte_tempo_cycle_jours_restants_bleu')}} / Blanc:
      {{states('sensor.rte_tempo_cycle_jours_restants_blanc')}} / Rouge:
      {{states('sensor.rte_tempo_cycle_jours_restants_rouge')}}
    icon: mdi:calendar-multiselect-outline
    icon_color: light-grey
    badge_color: ""
    fill_container: true
    layout: vertical
columns: 1
view_layout:
  position: sidebar
visibility:
  - condition: or
    conditions:
      - condition: numeric_state
        entity: sensor.rte_tempo_cycle_jours_restants_blanc
        above: 0
      - condition: numeric_state
        entity: sensor.rte_tempo_cycle_jours_restants_rouge
        above: 0

```
