### ISSUE TITLE
probleme sur l'historique du calendrier 

### ISSUE THREAD

**Issue by xtro83** [hekmon/rtetempo#9]
bonjour

l'historique des jours sur mon calendrier restent en bleu  par contre je ne sais pas si c'est un probleme de ma conf ou un bug ....
![2023-02-18_111755](https://user-images.githubusercontent.com/36260342/219855142-b7664877-7ce6-48d7-ae57-64dd6a628a54.jpg)

**Comment by hekmon** [comment]
Bonjour,

Étrange effectivement ! Si vous ouvrez un évènement du calendrier qu'affiche-t-il ?

Redémarrer Home Assistant devrait corriger le problème mais essayons de rassembler des infos avant.

**Comment by xtro83** [comment]
bonjour 

si j'ouvre un jour rouge par ex la couleur est bonne  l'onglet  de droite (celui des 3jours ) est ok egalement seul celui du mois n'affiche pas l'historique 
 j'ai dejà redemarré HA plusieurs fois mais c'est pareil 
je mets les copies  d'ecran 
![2023-02-19_095329](https://user-images.githubusercontent.com/36260342/219938654-ffd0a81e-43f0-41ad-9d22-619f3d9430b9.jpg)
![2023-02-19_095329](https://user-images.githubusercontent.com/36260342/219938661-b5e42e19-128e-4167-b520-718ae074f6f0.jpg)

**Comment by hekmon** [comment]
Je pense comprendre grâce à votre dernier screenshot !

La couleur bleu que vous voyez sur votre premier screenshot n'est pas la couleur bleu de tempo mais simplement la couleur home assistant de la présence d'un évènement !
![image](https://user-images.githubusercontent.com/3418467/219939005-cc4b298a-fb99-498d-8bd3-d5e3c0b16bc5.png)
![image](https://user-images.githubusercontent.com/3418467/219939000-37911001-c0fc-4568-a99b-b5f434f23472.png)
![image](https://user-images.githubusercontent.com/3418467/219939019-66b7e813-3530-4eca-8863-9ac64f218999.png)

Par contre ce que je ne m'explique pas c'est pourquoi/comment avez vous cet affichage... Quand je réduit mon Home Assistant au minimum, il me garde toujours le titre (qui est l'emoji de couleur) visible:
![image](https://user-images.githubusercontent.com/3418467/219939065-b0438d19-3a31-4bda-9709-e24e7841ae81.png)

Quelle est la version de votre Home Assistant ?

**Comment by xtro83** [comment]
c'est la 2023.2.1
effectivement si je clique sur un jour ( dans le calendrier mensuel ) par ex j'ai bien la couleur de l'evenement : 
![2023-02-19_102524](https://user-images.githubusercontent.com/36260342/219939830-400fd5cb-1a70-4aac-b12a-5a778346a02a.jpg)

**Comment by hekmon** [comment]
Cela devrait être suffisamment récent.

Je pense qu'il s'agit d'une fonctionnalité d'affichage côté Home Assistant, peut être quand l'espace d'affichage est limité, qui n'affiche qu'un point de couleur bleu sombre sur un jour pour indiqué qu'un évènement existe sans afficher son titre (qui est, dans le cas de cette extension, un emoji de couleur).

**Comment by xtro83** [comment]
je n'ai peut être pas cet emoji de couleur , où puis je le trouver ?

**Comment by hekmon** [comment]
Il fait parti des emoji standards, il n'y a pas besoin de le télécharger comme un codec. Et de ce que je vois du dernier screenshot que vous avez posté (celui d'affichage des détails de l'évènement jour rouge du 7 au 8 février) votre périphérique peut correctement les afficher.

Avez-vous essayé avec un autre périphérique pour en avoir le coeur net ?

**Comment by xtro83** [comment]
là je suis sous seven , je viens de regarder sur mon chromebook c'est pareil...

**Comment by hekmon** [comment]
Je comprends enfin, il s'agit d'un widget (une card) calendrier sur un dashboard lovelace et non de la vue calendrier globale (de laquelle mon screenshot provient).

De ce que je vois de la [documentation](https://www.home-assistant.io/dashboards/calendar/) il n'est pas possible d'afficher le nom des évènements sur la vue mois du calendrier. Seul un point de couleur (couleur représentant le calendrier affiché) apparait dans cette vue si un évènement est présent ce jour.

Je vois 2 solutions potentielles à votre problème:

- trouver une extension qui apporte un nouveau widget (une card dans le langage lovelace) calendrier qui afficherait le titre des éléments dans une vue mensuelle
- utiliser la vue calendrier globale de Home Assistant depuis le menu latéral (mais donc hors de votre dashboard personnalisé)

Je me permet de clore l'issue puisque le problème n'est pas lié à l'intégration en elle même mais à Home Assistant plus généralement. Cela n'empêche pas la discussion de se poursuivre.

**Comment by jisse44** [comment]
Salut,
J'ai été confronté au même soucis.
Solution : utiliser le module "atomic-calendar-revive" et l'ajouter via HACS
Le code pour avoir un Widget Calendrier : 

```
type: custom:atomic-calendar-revive
name: EDF Tempo
maxDaysToShow: 30
showMultiDay: false
showColors: true
defaultMode: Calendar
firstDayOfWeek: 1
startDaysAhead: -365
entities:
  - entity: calendar.rte_tempo_calendrier
    icon: mdi:lightning-bolt-circle
    color: blue
    allowlist: 🔵
  - entity: calendar.rte_tempo_calendrier
    icon: mdi:lightning-bolt-circle
    color: whitesmoke
    allowlist: ⚪
  - entity: calendar.rte_tempo_calendrier
    icon: mdi:lightning-bolt-circle
    color: red
    allowlist: 🔴
disableCalLocationLink: true
calShowDescription: true
disableCalLink: true
```
